// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECommerce_Project.Models;

public partial class UserOrder
{
    public int OrderId { get; set; }

    public string Uid { get; set; }

    public string Pid { get; set; }

    public int Quantity { get; set; }

    public DateTime? OrderDate { get; set; }

    public decimal? TotalAmount { get; set; }

    public string ShippingAddress { get; set; }

    public virtual Product PidNavigation { get; set; }

    public virtual User UidNavigation { get; set; }
}