// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ECommerce_Project.Models;

public partial class User
{
    public string Uid { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public virtual ICollection<UserOrder> UserOrders { get; set; } = new List<UserOrder>();
}

// DTOs for authentication
public class LoginRequest
{
    [Required]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    public string Password { get; set; }
}

public class RegisterRequest
{
    [Required]
    [EmailAddress]
    [MaxLength(255)]
    public string Email { get; set; }

    [Required]
    [MinLength(6)]
    [MaxLength(100)]
    public string Password { get; set; }
}

public class AuthenticatedResponse
{
    public string Token { get; set; }
    public DateTime ExpiresAtUtc { get; set; }
}
